export const cardArray = [
  {
    id: 0,
    title: "материал 1й сорт",
    price: "1700 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:44",
    img: "/images/Rectangle 3.png",
  },
  {
    id: 1,
    title: "материал 2й сорт",
    price: "1400 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 17:30",
    img: "/images/Rectangle 3.png",
  },
  {
    id: 2,
    title: "материал 3й сорт",
    price: "1100 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/images/Rectangle 3.png",
  },
  {
    id: 3,
    title: "материал 4й сорт",
    price: "800 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 11:33",
    img: "/images/Rectangle 3.png",
  },
  {
    id: 4,
    title: "материал 5й сорт",
    price: "500 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 23:39",
    img: "/images/Rectangle 3.png",
  },
  {
    id: 5,
    title: "материал 6й сорт",
    price: "170 ₽",
    address: "Казань, р-н Вахитовский",
    date: "10 июля 16:39",
    img: "/images/Rectangle 3.png",
  },
];
